PERSONAL_PROJECTS = [
    {"name": "Portfolio", "url": "https://mubassim.vercel.app/"},
    {"name": "Portfolio (Old)", "url": "https://mubassim-khan.netlify.app/"},
    {"name": "Zentry Clone", "url": "https://zentry-eight-weld.vercel.app/"},
    {"name": "IAD Project", "url": "https://grp-2.netlify.app/"},
    {"name": "QuizMaster AI", "url": "https://quizmaster-ai.streamlit.app/"},
    {"name": "Travel Journal", "url": "https://m-travel-journal.netlify.app/"},
    {"name": "CarHub", "url": "https://m-carhub.vercel.app/"},
    {"name": "Meme Generator", "url": "https://m-meme-generator.netlify.app/"},
    {"name": "Airbnb Experiences Clone", "url": "https://lively-bombolone-b2ef09.netlify.app"},
    {"name": "Imaginify AI", "url": "https://imaginify-ai-eight.vercel.app"},
    {"name": "Spotify Clone", "url": "https://spotify-clone-gt.vercel.app/"},
    {"name": "Business Card", "url": "https://m-business-card.netlify.app/"},
    {"name": "React Redux Toolkit", "url": "https://react-redux-toolkit-opal.vercel.app"},
    {"name": "Netflix Clone", "url": "https://netfflix-clone.netlify.app/"},
    {"name": "Dotcom Landing Page", "url": "https://m-dotcom.netlify.app/"},
    {"name": "iPhone Calculator", "url": "https://m-iphone-calculator.netlify.app/"},
    {"name": "Blogs Site", "url": "https://blog-page-nine-kappa.vercel.app/"},
    {"name": "ChatGPT AI", "url": "https://chatgpt-ai.streamlit.app/"},
]

SOCIAL_MEDIA = [
    {"name": "Google", "url": "https://www.google.com/"},
    {"name": "Instagram", "url": "https://www.instagram.com/"},
    {"name": "Facebook", "url": "https://www.facebook.com/"},
    {"name": "YouTube", "url": "https://www.youtube.com/"},
    {"name": "X (Twitter)", "url": "https://www.x.com/"},
    {"name": "WhatsApp", "url": "https://www.whatsapp.com/"},
    {"name": "Telegram", "url": "https://telegram.org/"},
    {"name": "Discord", "url": "https://discord.com/"},
    {"name": "GitHub", "url": "https://github.com/"},
    {"name": "LinkedIn", "url": "https://www.linkedin.com/"},
    {"name": "TikTok", "url": "https://www.tiktok.com/"},
    {"name": "Snapchat", "url": "https://www.snapchat.com/"},
    {"name": "Reddit", "url": "https://www.reddit.com/"},
    {"name": "Pinterest", "url": "https://www.pinterest.com/"},
    {"name": "Threads", "url": "https://www.threads.net/"},
]